apiVersion: apps/v1
kind: Deployment
metadata:
  name: provisioner
spec:
  replicas: 3
  selector:
    matchLabels:
      app: provisioner
  template:
    metadata:
      labels:
        app: provisioner
    spec:
      containers:
        - name: provisioner
          image: docker.io/folylyfo/provisioner:e9d246ac47667c74a91c45e0ed282e4df50aa2e0
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: provisioner-env
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
