apiVersion: apps/v1
kind: Deployment
metadata:
  name: provisioner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: provisioner
  template:
    metadata:
      labels:
        app: provisioner
    spec:
      containers:
        - name: provisioner
          image: docker.io/folylyfo/provisioner:c7be641034a103762353684c8185ae4fbbe6e3f1
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: provisioner-env
