apiVersion: apps/v1
kind: Deployment
metadata:
  name: provisioner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: provisioner
  template:
    metadata:
      labels:
        app: provisioner
    spec:
      containers:
        - name: provisioner
          image: docker.io/folylyfo/provisioner:09d1aa760bc7deeb20d6d0e9fcf7bbe222491098
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: provisioner-env
